### ISSUE TITLE
error rake

### ISSUE THREAD

**Issue by srem1** [bamchoh/mruby-toml#1]
$rake
(in /home/userek/mruby-3.1.0)
GIT CHECKOUT DETACH /home/userek/mruby-3.1.0/build/repos/host/mruby-toml -> 7119c282e62a3904cb273454607649d792bbe642
HEAD wskazuje teraz na 7119c28 Update README.md
CPP   build/repos/host/mruby-toml/src/mrb_toml.c -> build/host/mrbgems/mruby-toml/src/mrb_toml.pi
/home/userek/mruby-3.1.0/build/repos/host/mruby-toml/src/mrb_toml.c:19:10: fatal error: toml.h: Nie ma takiego pliku ani katalogu
   19 | #include "toml.h"
      |          ^~~~~~~~
compilation terminated.
rake aborted!
Command failed with status (1): [gcc -E -P -std=gnu99 -g -O3 -Wall -Wundef ...]
/home/userek/mruby-3.1.0/lib/mruby/build/command.rb:37:in `_run'
/home/userek/mruby-3.1.0/lib/mruby/build/command.rb:99:in `run'
/home/userek/mruby-3.1.0/lib/mruby/build/command.rb:120:in `block (2 levels) in define_rules'
/usr/share/gems/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Tasks: TOP => default => all => gensym => /home/userek/mruby-3.1.0/build/host/presym => /home/userek/mruby-3.1.0/build/host/mrbgems/mruby-toml/src/mrb_toml.pi
(See full trace by running task with --trace)

I dont know how testing this

**Comment by bamchoh** [comment]
Thank you very much for using my library :)
This library is depending on libtoml.
Before you execute `rake` command, you have to install libtoml in your environment.

**Comment by srem1** [comment]
1. how install toml lib , I use my project as embeded
2. please add this information on install/web page

**Comment by bamchoh** [comment]
Please see the below link about libtoml

https://github.com/ajwans/libtoml

I'm sorry. As of now, I am not actively working on this library.

If you need a toml parser, I suggest you build your own :)
